# Installs memcached

- name: Install memcached
  apt:
    name: memcached
    state: present
    update_cache: yes
  tags:
    - install
    - install:memcache

- name : allow memcache from remote
    path: /etc/memcached.conf
    regexp: '^\-l 127\.0\.0\.1'
    line: '-l 0.0.0.0'
