---
codejail_debian_packages:
  - apparmor-utils
CODEJAIL_PYTHON_VERSIONS:
  - python2.7
  - python3.5
  - python3.6
codejail_python_versions: "{{ CODEJAIL_PYTHON_VERSIONS }}"
codejail_sandbox_user: 'sandbox'
codejail_sandbox_group: 'sandbox'
codejail_sandbox_name_base: 'codejail_sandbox'
codejail_sandbox_env: '/home/{{ codejail_sandbox_user }}/{{ codejail_sandbox_name_base }}'
codejail_sandbox_caller: 'ubuntu'
