###################################################################################
############################ TO BE MODIFIED #######################################
## WUL_HOSTS
WUL_SITE_FQDN: 'weup.in'
WUL_MYSQL_SERVER: 'ip-XXX-YYY-ZZZ-AAAA.eu-west-1.compute.internal'
WUL_PERSISTANCE_SERVER: 'ip-XXX-YYY-ZZZ-AAAA.eu-west-1.compute.internal'
WUL_REMOTE_IP_PERSISTANCE: 'ip-XXX-YYY-ZZZ-AAAA.eu-west-1.compute.internal'

## GENERIC
WUL_PLATFORM_NAME: 'WeUp Learning'

## EMAIL SERVER
EDXAPP_EMAIL_HOST: 'FILL_IN_WITH_STMP_HOST_IF_NEEDED_CHANGE_THE_TWO_FIELDS_BELOW'
EDXAPP_EMAIL_PORT: 25
EDXAPP_EMAIL_USE_TLS: True
EDXAPP_EMAIL_HOST_USER: 'FILL_IN_WITH_STMP_USER'
EDXAPP_EMAIL_HOST_PASSWORD: 'FILL_IN_WITH_STMP_PASSWD'

## EMAIL ADRESSES
EDXAPP_DEFAULT_FROM_EMAIL: "FILL_IN"
EDXAPP_CONTACT_EMAIL: "FILL_IN"
EDXAPP_BUGS_EMAIL: "FILL_IN"

#SSL CERTIFICATES
REDIRECT_NGINX_SSL_CERTIFICATE: 'ssl-cert-snakeoil.pem'
REDIRECT_NGINX_SSL_KEY: 'ssl-cert-snakeoil.key'

###################################################################################
############################ NOT TO BE MODIFIED ###################################
###################################################################################
# EDX ATP REPO
edx_platform_repo: "https://github.com/weuplearning/edx-platform.git"
edx_platform_version: 'wul_master'

## GENERIC
EDXAPP_LMS_NGINX_PORT: 80
EDXAPP_LMS_SSL_NGINX_PORT: 443
EDXAPP_CMS_NGINX_PORT: 80
EDXAPP_CMS_SSL_NGINX_PORT: 443

EDXAPP_PLATFORM_NAME: '{{ WUL_PLATFORM_NAME }}'
EDXAPP_STUDIO_NAME: 'Studio {{ WUL_PLATFORM_NAME }}'
EDXAPP_STUDIO_SHORT_NAME: 'Studio {{ WUL_PLATFORM_NAME }}'

EDXAPP_LMS_SITE_NAME: '{{ WUL_SITE_FQDN }}'
EDXAPP_CMS_SITE_NAME: 'studio.{{ WUL_SITE_FQDN }}'
EDXAPP_LMS_BASE: '{{ WUL_SITE_FQDN }}'
EDXAPP_CMS_BASE: 'studio.{{ WUL_SITE_FQDN }}'

## BASIC SSL SUPPORT (except certificates)
NGINX_ENABLE_SSL: True
NGINX_REDIRECT_TO_HTTPS: True
REDIRECT_NGINX_ENABLE_SSL: True
EDXAPP_SESSION_COOKIE_SECURE: True
EDXAPP_SESSION_COOKIE_DOMAIN: "{{ WUL_SITE_FQDN }}"
EDXAPP_CSRF_COOKIE_SECURE: True
ECOMMERCE_SESSION_COOKIE_SECURE: True
ECOMMERCE_CSRF_COOKIE_SECURE: True

## ENABLE SSO
EDXAPP_ENABLE_THIRD_PARTY_AUTH: True

## EMAIL
EDXAPP_API_ACCESS_FROM_EMAIL: "{{ EDXAPP_BUGS_EMAIL }}"
EDXAPP_API_ACCESS_MANAGER_EMAIL: "{{ EDXAPP_BUGS_EMAIL }}"
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: "{{ EDXAPP_DEFAULT_FROM_EMAIL }}"
EDXAPP_DEFAULT_FEEDBACK_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_DEFAULT_SERVER_EMAIL: "{{ EDXAPP_BUGS_EMAIL }}"
EDXAPP_FEEDBACK_SUBMISSION_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_PARTNER_SUPPORT_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_PAYMENT_SUPPORT_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_PRESS_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_SERVER_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_TECH_SUPPORT_EMAIL: "{{ EDXAPP_BUGS_EMAIL }}"
EDXAPP_UNIVERSITY_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"

## MYSQL
EDXAPP_MYSQL_USER: 'edxapp001'
EDXAPP_MYSQL_USER: 'edxapp_csmh001'
ECOMMERCE_MYSQL_USER: 'ecommerce001'
XQUEUE_MYSQL_USER: 'xqueue001'
#EDX_NOTES_API_MYSQL_DB_USER: 'edx_notes001'
ANALYTICS_PIPELINE_OUTPUT_DATABASE_USER: 'pipeline001'
ANALYTICS_API_DEFAULT_USER: 'api001'
ANALYTICS_API_REPORTS_USER: 'reports001'
BLOCKSTORE_MYSQL_USER: 'blockstore001'
CREDENTIALS_MYSQL_USER: 'credentials001'
DISCOVERY_MYSQL_USER: 'discov001'
VIDEO_PIPELINE_BASE_MYSQL_USER: 'veda001'
REGISTRAR_MYSQL_USER: 'registrar001'

EDXAPP_MYSQL_DB_NAME: 'edxapp'
EDXAPP_MYSQL_CSMH_DB_NAME: 'edxapp_csmh'
ECOMMERCE_DATABASE_NAME: 'ecommerce'
XQUEUE_MYSQL_DB_NAME: 'xqueue'
EDX_NOTES_API_MYSQL_DB_NAME: 'edx_notes'
ANALYTICS_API_DEFAULT_DB_NAME: 'analytics_api_default'
ANALYTICS_API_REPORTS_DB_NAME: 'analytics_api_reports'
BLOCKSTORE_DEFAULT_DB_NAME: 'blockstore'
CREDENTIALS_DEFAULT_DB_NAME: 'credentials'
DISCOVERY_DEFAULT_DB_NAME: 'discovery'
VEDA_WEB_FRONTEND_DEFAULT_DB_NAME: 'veda'
REGISTRAR_DEFAULT_DB_NAME: 'registrar'



XQUEUE_MYSQL_HOST: '{{ WUL_MYSQL_SERVER }}'
EDXAPP_MYSQL_HOST: '{{ WUL_MYSQL_SERVER }}'
CREDENTIALS_MYSQL_HOST: '{{ WUL_MYSQL_SERVER }}'
EDX_NOTES_API_MYSQL_HOST: '{{ WUL_MYSQL_SERVER }}'
VEDA_WEB_FRONTEND_MYSQL_HOST: '{{ WUL_MYSQL_SERVER }}'
DESIGNER_MYSQL_HOST: '{{ WUL_MYSQL_SERVER }}'
REGISTRAR_MYSQL_HOST: '{{ WUL_MYSQL_SERVER }}'
VIDEO_PIPELINE_BASE_MYSQL_HOST: '{{ WUL_MYSQL_SERVER }}'
ENTERPRISE_CATALOG_MYSQL_HOST: '{{ WUL_MYSQL_SERVER }}'


## MONGO, RBMQ, ES, MC
EDXAPP_MONGO_HOSTS: ['{{ WUL_PERSISTANCE_SERVER }}']
FORUM_MONGO_HOSTS: ['{{ WUL_PERSISTANCE_SERVER }}']

rabbitmq_ip: '{{ WUL_PERSISTANCE_SERVER }}'
XQUEUE_RABBITMQ_HOSTNAME: '{{ WUL_PERSISTANCE_SERVER }}'
EDXAPP_RABBIT_HOSTNAME: '{{ WUL_PERSISTANCE_SERVER }}'

EDXAPP_MEMCACHE : [ '{{ WUL_PERSISTANCE_SERVER }}:11211' ]
DISCOVERY_MEMCACHE: [ '{{ WUL_PERSISTANCE_SERVER }}:11211' ]
DESIGNER_MEMCACHE: [ '{{ WUL_PERSISTANCE_SERVER }}:11211' ]
ECOMMERCE_MEMCACHE: [ '{{ WUL_PERSISTANCE_SERVER }}:11211' ]
ENTERPRISE_CATALOG_MEMCACHE: [ '{{ WUL_PERSISTANCE_SERVER }}:11211' ]
VEDA_WEB_FRONTEND_MEMCACHE: [ '{{ WUL_PERSISTANCE_SERVER }}:11211' ]

FORUM_ELASTICSEARCH_HOST: '{{ WUL_PERSISTANCE_SERVER }}'
DISCOVERY_ELASTICSEARCH_URL: 'http://{{ WUL_PERSISTANCE_SERVER }}:9200/'
EDX_NOTES_API_ELASTICSEARCH_URL: 'http://{{ WUL_PERSISTANCE_SERVER }}:9200/'

