###################################################################################
############################ TO BE MODIFIED #######################################
## ATP_HOSTS
ATP_SITE_FQDN: 'THE_FQDN_FOR_LMS'
ATP_MYSQL_SERVER: 'ip-XXX-YYY-ZZZ-AAAA.eu-west-1.compute.internal'
ATP_PERSISTANCE_SERVER: 'ip-XXX-YYY-ZZZ-AAAA.eu-west-1.compute.internal'
ATP_REMOTE_IP_PERSISTANCE: 'ip-XXX-YYY-ZZZ-AAAA.eu-west-1.compute.internal'

## GENERIC
ATP_PLATFORM_NAME: 'Demo ATP'

## EMAIL SERVER
EDXAPP_EMAIL_HOST: 'FILL_IN_WITH_STMP_HOST_IF_NEEDED_CHANGE_THE_TWO_FIELDS_BELOW'
EDXAPP_EMAIL_PORT: 587
EDXAPP_EMAIL_USE_TLS: True
EDXAPP_EMAIL_HOST_USER: 'FILL_IN_WITH_STMP_USER'
EDXAPP_EMAIL_HOST_PASSWORD: 'FILL_IN_WITH_STMP_PASSWD'

## EMAIL ADRESSES
EDXAPP_DEFAULT_FROM_EMAIL: "FILL_IN"
EDXAPP_CONTACT_EMAIL: "FILL_IN"
EDXAPP_BUGS_EMAIL: "FILL_IN"

#SSL CERTIFICATES
REDIRECT_NGINX_SSL_CERTIFICATE: 'ssl-cert-snakeoil.pem'
REDIRECT_NGINX_SSL_KEY: 'ssl-cert-snakeoil.key'

###################################################################################
############################ NOT TO BE MODIFIED ###################################
###################################################################################
# EDX ATP REPO
edx_platform_repo: "https://github.com/weuplearning/edx-platform.git"
edx_platform_version: 'atp_juniper'

## GENERIC
EDXAPP_LMS_NGINX_PORT: 80
EDXAPP_LMS_SSL_NGINX_PORT: 443
EDXAPP_CMS_NGINX_PORT: 80
EDXAPP_CMS_SSL_NGINX_PORT: 443

EDXAPP_PLATFORM_NAME: '{{ ATP_PLATFORM_NAME }}'
EDXAPP_STUDIO_NAME: 'Studio {{ ATP_PLATFORM_NAME }}'
EDXAPP_STUDIO_SHORT_NAME: 'Studio {{ ATP_PLATFORM_NAME }}'

EDXAPP_LMS_SITE_NAME: '{{ ATP_SITE_FQDN }}'
EDXAPP_CMS_SITE_NAME: 'studio.{{ ATP_SITE_FQDN }}'
EDXAPP_LMS_BASE: '{{ ATP_SITE_FQDN }}'
EDXAPP_CMS_BASE: 'studio.{{ ATP_SITE_FQDN }}'

## BASIC SSL SUPPORT (except certificates)
NGINX_ENABLE_SSL: True
NGINX_REDIRECT_TO_HTTPS: True
REDIRECT_NGINX_ENABLE_SSL: True
EDXAPP_SESSION_COOKIE_SECURE: True
EDXAPP_SESSION_COOKIE_DOMAIN: "{{ ATP_SITE_FQDN }}"
EDXAPP_CSRF_COOKIE_SECURE: True

## ENABLE SSO
EDXAPP_ENABLE_THIRD_PARTY_AUTH: True

## EMAIL
EDXAPP_API_ACCESS_FROM_EMAIL: "{{ EDXAPP_BUGS_EMAIL }}"
EDXAPP_API_ACCESS_MANAGER_EMAIL: "{{ EDXAPP_BUGS_EMAIL }}"
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: "{{ EDXAPP_DEFAULT_FROM_EMAIL }}"
EDXAPP_DEFAULT_FEEDBACK_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_DEFAULT_SERVER_EMAIL: "{{ EDXAPP_BUGS_EMAIL }}"
EDXAPP_FEEDBACK_SUBMISSION_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_PARTNER_SUPPORT_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_PAYMENT_SUPPORT_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_PRESS_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_SERVER_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_TECH_SUPPORT_EMAIL: "{{ EDXAPP_BUGS_EMAIL }}"
EDXAPP_UNIVERSITY_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"

## MYSQL
EDXAPP_MYSQL_DB_NAME: 'edxapp'
EDXAPP_MYSQL_CSMH_DB_NAME: 'edxapp_csmh"
XQUEUE_MYSQL_HOST: '{{ ATP_MYSQL_SERVER }}'
EDXAPP_MYSQL_HOST: '{{ ATP_MYSQL_SERVER }}'
CREDENTIALS_MYSQL_HOST: '{{ ATP_MYSQL_SERVER }}'
EDX_NOTES_API_MYSQL_HOST: '{{ ATP_MYSQL_SERVER }}'

## MONGO, RBMQ, ES, MC
EDXAPP_MONGO_HOSTS: ['{{ ATP_PERSISTANCE_SERVER }}']
FORUM_MONGO_HOSTS: ['{{ ATP_PERSISTANCE_SERVER }}']

rabbitmq_ip: '{{ ATP_PERSISTANCE_SERVER }}'
XQUEUE_RABBITMQ_HOSTNAME: '{{ ATP_PERSISTANCE_SERVER }}'
EDXAPP_RABBIT_HOSTNAME: '{{ ATP_PERSISTANCE_SERVER }}'

EDXAPP_MEMCACHE : [ '{{ ATP_PERSISTANCE_SERVER }}:11211' ]
INSIGHTS_MEMCACHE: [ '{{ ATP_PERSISTANCE_SERVER }}:11211' ]

FORUM_ELASTICSEARCH_HOST: '{{ ATP_PERSISTANCE_SERVER }}'
DISCOVERY_ELASTICSEARCH_URL: 'http://{{ ATP_PERSISTANCE_SERVER }}:9200/'
EDX_NOTES_API_ELASTICSEARCH_URL: 'http://{{ ATP_PERSISTANCE_SERVER }}:9200/'

