- name: Setup Whitelabel themes
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_DATADOG: False
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'discovery'
  vars_files:
    - "roles/edxapp/defaults/main.yml"
    - "roles/discovery/defaults/main.yml"
    - "roles/ecommerce/defaults/main.yml"
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - edxlocal
    - role: nginx
      nginx_default_sites:
        - discovery
    - discovery
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
    - role: datadog-uninstall
      when: not COMMON_ENABLE_DATADOG
    - whitelabel
